on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup env
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Setup virtual env
        run: |
          pipenv install
      
      - name: Install black
        run:
          pipenv install black
      
      - name: Run black linter
        run:
          pipenv run black -v .