on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup env
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: |
          python -m pip install pipenv
      
      - name: Setup and run black linter
        run: |
          pipenv install black
          pipenv run black -v .