on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup env
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup virtual env
        run: |
          python -m pip install -r requirements.txt
      
      - name: Install black
        run:
          pip install black
      
      - name: Run black linter
        run:
          black -v .