name: Push build to docker hub
on: push


jobs:
  publish_to_docker:
    runs-on: self-hosted 
    steps:
      - name: Set up Env
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }} 
        run: echo $DOCKER_USERNAME
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
            
      - name: Build and push app image to Docker
        uses: docker/build-push-action@v4
        with:
            context: .
            push: true
            tags: ajitshrivastav/pastebin:latest