name: Push build to docker hub
on: push

env:
  IMAGE_NAME: ajitshrivastav/pastebin

jobs:
  publish_to_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Env
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }} 
        run: echo $DOCKER_USERNAME
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: ${{ env.IMAGE_NAME }}
    
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
            sbom: true
            push: true
            tags: ${{ steps.meta.outputs.tags }}
