name: Run tests 
on:
  push:
      branches: [ main ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}  

    steps:

      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Setup env
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup virtual env
        run: |
          python -m pip install -r requirements.txt

      - name: Debug info
        run: |
          python --version
          pwd
          ls -l

      - name: Run tests
        run: python -m unittest app_test.py