name: Run tests 
on:
  pull_request:
    branches: [ "main" ]
jobs:
  run_tests_on_merge:
    runs-on: ubuntu-latest 
    steps:
      - name: Run tests on merge 
        run: echo "To add trigger for running test cases on merge"
