name: Run tests 
on: push

jobs:
  build:
    runs-on: ubuntu-latest 
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}  

    steps:

      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Setup env
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install pipenv
        run: |
          python -m pip install pipenv
      
      - name: Debug info
        run: |
          pipenv run python --version
          pwd
          ls -l
          pipenv requirements

      - name: Run tests
        run: |
          pipenv install -v
          pipenv run python -m unittest -q app_test.py