name: Run tests 
on: push

jobs:
  build:
    runs-on: ubuntu-latest 
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}  

    steps:

      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Setup env
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup virtual env
        run: |
          python -m pip install pipenv
          pipenv install
          pipenv shell


      - name: Debug info
        run: |
          python --version
          pwd
          ls -l
          pipenv requirements

      - name: Run tests
        run: python -m unittest -q app_test.py