name: Run tests 
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Setup env
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup virtual env
        run: |
          python -m pip install -r requirements.txt

      - name: Debug info
        run: |
          python --version
          echo "Working dir ${pwd}"
          echo "Dir contents ${ls -l}"
          echo "Contents site packages - ${ls -l /venv/lib/python*/site-packages}"

      - name: Run tests
        run: python -m unittest app_test.py