name: Generate SBOM
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "ajit" ]

jobs:
  build:
    runs-on: ubuntu-latest 
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
