name: Run tests 
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "ajit" ]

jobs:
  build:
    runs-on: ubuntu-latest 
  
    steps:
      - name: Run Trivy scanner without cache
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          cache: 'false'