on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        base: f5a3d63f1d954fc12a9458062b4b4782b6c24085
        head: 82cdf38744e602851440794d8360709bfeb4484b
        extra_args: --debug