name: Security check 
on:
  pull_request:
    branches: [ "main" ]
jobs:
  security_check_on_merge:
    runs-on: ubuntu-latest 
    steps:
      - name: Security check on merge 
        run: echo "Add security checks"
