name: Security check 
on:
  pull_request:
    branches: [ "main" ]
jobs:
  security_check_on_merge:
    runs-on: ubuntu-latest 
    steps:
      - name: Check signed commits in PR
        run: 1Password/check-signed-commits-action@v1
