name: Snyk scanning
on: 
  pull_request:
    branches: [ "ajit" ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Run Snyk vulnerability scanning
        uses: snyk/actions/python-3.10@master
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        